version: "3.2"

services:

  message-queue:
    image: nats:nanoserver
#    ports:
#      - mode: host
#        target: 4222
#        published: 4222
    networks:
      - nd-net
    deploy:    
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.platform.os == windows'
      labels:
        app.name: nerd-dinner

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
#    ports:
#      - mode: host
#        target: 9200
#        published: 9200
    volumes:
      - es-data:c:\data
    networks:
      - nd-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.platform.os == windows'          
      labels:
        app.name: nerd-dinner

  nerd-dinner-db:
    image: dockeronwindows/ch06-nerd-dinner-db
#    ports:
#      - mode: host
#        target: 1433
#        published: 1433
    environment:
      - sa_password=4jsZedB32!iSm__
    volumes:
      - db-data:c:\database
    networks:
      - nd-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.platform.os == windows'
      labels:
        app.name: nerd-dinner

  kibana:
    image: sixeyed/kibana:nanoserver
    ports:
      - mode: host
        target: 5601
        published: 5601
    networks:
      - nd-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.platform.os == windows'
      labels:
        app.name: nerd-dinner

  nerd-dinner-save-handler:
    image: dockeronwindows/ch05-nerd-dinner-save-handler
    environment:
      - APP_DB_CONNECTION_STRING=Data Source=nerd-dinner-db,1433;Initial Catalog=NerdDinner;User Id=sa;Password=4jsZedB32!iSm__;MultipleActiveResultSets=True;
    networks:
      - nd-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.platform.os == windows'
      labels:
        app.name: nerd-dinner

  nerd-dinner-index-handler:
    image: dockeronwindows/ch05-nerd-dinner-index-handler
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
    networks:
      - nd-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.platform.os == windows'          
      labels:
        app.name: nerd-dinner

  nerd-dinner-homepage:
    image: dockeronwindows/ch03-nerd-dinner-homepage
#    ports:
#      - mode: host
#        target: 5000
#        published: 5000
    networks:
      - nd-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.platform.os == windows'
      labels:
        app.name: nerd-dinner

  nerd-dinner-web:
    image: dockeronwindows/ch05-nerd-dinner-web
    ports:
      - mode: host
        target: 8081
        published: 8081
    environment: 
      - HOMEPAGE_URL=http://nerd-dinner-homepage:5000
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - AUTH_DB_CONNECTION_STRING=Data Source=nerd-dinner-db,1433;Initial Catalog=NerdDinner;User Id=sa;Password=4jsZedB32!iSm__;
      - APP_DB_CONNECTION_STRING=Data Source=nerd-dinner-db,1433;Initial Catalog=NerdDinner;User Id=sa;Password=4jsZedB32!iSm__;MultipleActiveResultSets=True;
    networks:
      - nd-net
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.platform.os == windows'
      labels:
        app.name: nerd-dinner

networks:
  nd-net:

volumes:
  es-data:
  db-data: