version: '3'

services:
  
  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    networks:
      - elk-net

  kibana:
    image: sixeyed/kibana:nanoserver
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

networks:
  elk-net: